@INVALID_ORDER_ID = 3eb2af5bbaa58dd422e84d8
@ORCL_ORDER_ID = 9c49e168d5c32e97f97fd105

### NOTE: Replace the value of the variable ORCL_ORDER_ID with the value
###     of "id" in the response of the following request, i.e., Request 1.
###     Don't change the value of the variable INVALID_ORDER_ID

### Request 1: Create an order
### Response
### Status Code: 201
### Body: JSON for the newly created order with 4 properties
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "ORCL",
    "quantity": 10
}

### Request 2: Create another order
### Response
### Status Code: 201
### Body: JSON for the newly created order with 4 properties
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "MSFT",
    "quantity": 12
}

### Request 3: Create another order
### Response
### Status Code: 201
### Body: JSON for the newly created order with 4 properties
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "ORCL",
    "quantity": 4
}

### Request 4: Create another order
### Response
### Status Code: 201
### Body: JSON for the newly created order with 4 properties
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "MSFT",
    "quantity": 13
}

### Request 5: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "MST",
    "quantity": 0
}


### Request 6: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "M",
    "quantity": 10
}


### Request 7: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": 10,
    "quantity": 10
}

### Request 8: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "MSFT"
}


### Request 9: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "MSFT",
    "quantity": 10.5
}

### Request 10: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "company": "MSFT",
    "quantity": "10"
}


### Request 11: Invalid request for order creation
### Response
### Status Code: 400
### Body: {"Error": "Invalid request"}
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
    "quantity": 10
}

### Request 12: Retrieve all
### Response
### Status Code: 200 
### Body: An array with 6 orders, 4 new orders, plus the 2 orders that
###             were pre-existing in the file 'data/orders.mjs'
GET http://localhost:3000/orders HTTP/1.1


### Request 13: Retrieve orders for ORCL
### Response
### Status Code: 200 
### Body: An array with the 3 orders for ORCL
GET http://localhost:3000/orders?company=ORCL HTTP/1.1

### Request 14: Retrieve orders for MSFT
### Response
### Status Code: 200 
### Body: An array with the 3 orders for MSFT
GET http://localhost:3000/orders?company=MSFT HTTP/1.1

### Request 15: Retrieve orders for DELL
### Response
### Status Code: 200 
### Body: An empty array
GET http://localhost:3000/orders?company=DELL HTTP/1.1

### Request 16: Retrieve by ID.
### Response
### Status Code: 200 
### Body: JSON with 4 properties. company: ORCL, quantity: 10
GET http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1


### Request 17: Retrieve by invalid ID
### Response
### Status Code: 404 status code
### Body: {"Error": "Not found"}
GET http://localhost:3000/orders/{{INVALID_ORDER_ID}} HTTP/1.1


### Request 18: Edit order for ORCL
### Response
### Status Code: 200
### Body: JSON with 4 properties. company: ORCL, quantity: 99
PUT http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1
content-type: application/json

{
    "quantity": 99
}

### Request 19: Verify that quantity is now 99
### Response
### Status Code: 200
### Body: JSON with 4 properties. company: ORCL, quantity: 99
GET http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1


### Request 20: Edit order with invalid ID
### Response
### Status Code: 404
### Body: {"Error": "Not found"}
PUT http://localhost:3000/orders/{{INVALID_ORDER_ID}} HTTP/1.1
content-type: application/json

{
    "quantity": 109
}


### Request 21: Edit order with invalid body
### Response
### Status Code: 400 status code
### Body {"Error": "Invalid request"}
PUT http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1
content-type: application/json

{
    "quant": 109
}

### Request 22: Edit order with invalid body
### Response
### Status Code: 400 status code
### Body {"Error": "Invalid request"}
PUT http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1
content-type: application/json

{
    "quantity": "109"
}

### Request 23: Edit order with invalid body
### Response
### Status Code: 400 status code
### Body {"Error": "Invalid request"}
PUT http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1
content-type: application/json

{
    "quantity": -1
}


### Request 24: Delete order
### Response
### Status Code: 204 status code
### Body: empty
DELETE http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1


### Request 25: Retrieve order just deleted
### Response
### Status Code: 404 status code
### Body: {"Error": "Not found"}
GET http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1


### Request 26: Delete order just deleted
### Response
### Status Code: 404 status code
### Body: {"Error": "Not found"}
DELETE http://localhost:3000/orders/{{ORCL_ORDER_ID}} HTTP/1.1


### Request 27: Verify that the order has been deleted
### Response
### Status Code: 200
### Body: Array must contain 5 orders and must not contain the order for
###     ORCL created by Request 1 (with quantity 10, later updated to 99)
GET http://localhost:3000/orders HTTP/1.1
