"""
IMPORTANT NOTE:
---------------
The provided code is based on the general implementation of Breadth-First Search (BFS) 
using a queue data structure. This is the most common and standard way of implementing BFS. 
However, you are welcome to try your own approach or other variations of BFS as long as 
they produce correct results.
"""

from collections import deque

def bfs(graph: dict[str, list[str]], start: str, end: str) -> tuple[dict[str, str | None], list[str]]:
    """
    Perform Breadth-First Search (BFS) on a graph to explore all reachable nodes 
    and record parent-child relationships for path reconstruction.

    Parameters
    ----------
    graph : dict[str, list[str]]
        Adjacency list of the graph, where each key is a node and the value is a list of neighbor nodes.
    start : str
        The starting node for BFS.
    end : str
        The goal node to search for.

    Variables
    ----------
    queue : collections.deque
        FIFO queue to manage nodes to be explored.
    parent_map : dict[str, str | None]
        Maps each visited node to its parent. Start node has value None.
    expansion_order : list[str]
        List of nodes in the order they were expanded.

    Returns
    -------
    tuple
        parent_map : dict[str, str | None]
            Mapping of nodes to parents for path reconstruction.
        expansion_order : list[str]
            Order in which nodes were expanded.
    """
    queue = deque([start])
    parent_map = {start: None}
    expansion_order = []


    children = graph[start]
    #print(len(children))
    print(children) # 123
    print(graph[children[0]]) # 45
    children = graph[children[1][0]]
    print(graph[children[0]]) # 4's children
    

    while(end not in queue):
        for child in children:
            queue.append(child) # add current nodes children to frontier list

        # for each depth
        current_node = queue.popleft()   # remove recent node from queue/frontier list and save as the node to be expanded
        expansion_order.append(current_node) # expansion list
        if current_node == end: # node in frontier list
            break
        for child in graph[current_node]: # navigate dict with graph[current_node], look at each child for depth
            if child not in parent_map:
                queue.append(child)
                parent_map[child] = current_node    

    return parent_map, expansion_order


def backtracking(parent_map: dict[str, str | None], goal_node: str = 'G') -> list[str]:
    """
    Reconstruct the path from the start node to the goal node using the parent map.

    Parameters
    ----------
    parent_map : dict[str, str | None]
        Dictionary mapping child -> parent node created by BFS.
    goal_node : str, optional
        The goal node (default is 'G').

    Variables
    ----------
    path : list[str]
        List of nodes representing the reconstructed path from goal to start.
    node : str
        Current node during backtracking.

    Returns
    -------
    list[str]
        Ordered list of nodes from start to goal.
    """
    path = []
    node = goal_node
    while node is not None:
        path.append(node)
        node = parent_map[node]
    return path[::-1]


def display(list_of_nodes: list[str]) -> None:
    """
    Print a sequence of nodes in arrow-separated format.

    Parameters
    ----------
    list_of_nodes : list[str]
        List of nodes to display.

    Returns
    -------
    None
    """
    print(" -> ".join(list_of_nodes))


def main() -> None:
    """
    Demonstrate BFS traversal and path reconstruction on a sample graph.

    Variables
    ----------
    graph : dict[str, list[str]]
        Adjacency list representing the graph.
    parent_map : dict[str, str | None]
        Parent map generated by BFS.
    expansion_order : list[str]
        Order in which nodes were expanded during BFS.
    path : list[str]
        Shortest path from start to goal reconstructed using parent map.

    Returns
    -------
    None
    """
    graph = {
        'S': ['1', '2', '3'],
        '1': ['4', '5'],
        '2': ['6', '7', '8'],
        '3': ['9'],
        '4': ['10', '11'],
        '5': ['G', '12'],
        '6': ['13', '14'],
        '7': ['15', '16'],
        '8': ['17', '18'],
        '9': ['19'],
        'G': [],
        '10': [], '11': [], '12': [], '13': [], '14': [],
        '15': [], '16': [], '17': [], '18': [], '19': []
    }

    parent_map, expansion_order = bfs(graph, 'S', 'G')
    if 'G' in parent_map:
        path = backtracking(parent_map, 'G')
    else:
        path = None

    print("BFS Expansion Order:")
    display(expansion_order)

    # Print the path
    if path:
        print("BFS Path Found:")
        display(path)
    else:
        print("No path found.")


if __name__ == "__main__":
    main()
